platform :ios do
  desc "Deploy ios app on the appstore"

  lane :deploy do
    match(type: "appstore")
    ionic(platform: 'ios')
    deliver(ipa: ENV('CAPACITOR_IOS_RELEASE_BUILD_PATH'))
  end
end

platform :android do
  desc "Deploy android app on play store"

  lane :deploy do
    ionic(
      platform: 'android',
      keystore_path: './prod.keystore',
      keystore_alias: 'prod',
      keystore_password: 'password',
      build_flag: ['-UseModernBuildSystem=0']
    )
    supply(apk: ENV('CAPACITOR_ANDROID_RELEASE_BUILD_PATH'))
  end
end
