name: Ruby Gem

on:
  release:
    types: [created]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies for Ruby build
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev \
                                libyaml-dev libgmp-dev libncurses5-dev \
                                libffi-dev git curl autoconf bison build-essential

    - name: Install ruby-build
      run: |
        git clone https://github.com/rbenv/ruby-build.git
        sudo ./ruby-build/install.sh

    - name: Build and install Ruby 3.3.0 into toolcache
      run: |
        RUBY_VERSION=3.3.0
        INSTALL_DIR="/opt/hostedtoolcache/Ruby/$RUBY_VERSION/x64"

        sudo mkdir -p "$INSTALL_DIR"
        sudo ruby-build "$RUBY_VERSION" "$INSTALL_DIR"

        # Mark as complete
        sudo touch "$INSTALL_DIR.complete"

        # Add to PATH
        echo "export PATH=$INSTALL_DIR/bin:\$PATH" >> "$GITHUB_ENV"
        echo "export RUBY_ROOT=$INSTALL_DIR" >> "$GITHUB_ENV"

    - name: Verify Ruby installation
      run: |
        ruby -v
        gem -v
        
    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
