name: Ruby Gem

on:
  release:
    types: [created]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
        # Set up
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@2e007403fc1ec238429ecaa57af6f22f019cc135 # v1.234.0
      with:
        bundler-cache: true
        ruby-version: ruby

    # Release
    - uses: rubygems/release-gem@9e85cb11501bebc2ae661c1500176316d3987059 # v1
